version: '3.9'
services:
  bidding-bud-db:
    image: postgres
    restart: always
    container_name: bidding-bud-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
